### ISSUE TITLE
Fail to build on bs-platform@1.7.5

### ISSUE THREAD

**Issue by jackalcooper** [OvermindDL1/bucklescript-tea#26]
```
[6/27] Building src/web_location.cmj /Users/jackalcooper/elixir/node_modules/bucklescript-tea/lib/js/src/web_location.js src/web_location.cmi
FAILED: src/web_location.cmj /Users/jackalcooper/elixir/node_modules/bucklescript-tea/lib/js/src/web_location.js src/web_location.cmi 
/Users/jackalcooper/elixir/missing_pieces/assets/node_modules/bs-platform/bin/bsc.exe -bs-package-name bucklescript-tea  -bs-package-output commonjs:lib/js/src -bs-assume-no-mli -bs-no-builtin-ppx-ml -bs-no-implicit-include  -I src  -nostdlib -I '/Users/jackalcooper/elixir/node_modules/bs-platform/lib/ocaml' -bs-cross-module-opt -no-alias-deps -color always -w -40+6+7+27+32..39+44+45 -o src/web_location.mlast -c  src/web_location.mlast 
File "/Users/jackalcooper/elixir/node_modules/bucklescript-tea/src/web_location.ml", line 3, characters 9-433:
Error: Unbound module Js.Internal
ninja: build stopped: subcommand failed.
Failure: /Users/jackalcooper/elixir/missing_pieces/assets/node_modules/bs-platform/bin/ninja.exe 
 Location: /Users/jackalcooper/elixir/node_modules/bucklescript-tea/lib/bs
Error happened when running command /Users/jackalcooper/elixir/missing_pieces/assets/node_modules/bs-platform/bin/bsb.exe with args [ '-make-world', '-w' ]
```

**Comment by jackalcooper** [comment]
```
File "/Users/jackalcooper/elixir/missing_pieces/assets/node_modules/bucklescript-tea/src/web_xmlhttprequest.ml", line 89, characters 20-42:
Warning 3: deprecated: Js.String.splitLimited
Please use splitAtMost
[16/32] Building src/tea_json.cmj /Users/jackalcooper/elixir/missing_p...es/assets/node_modules/bucklescript-tea/lib/js/src/tea_json.js src/tea_json.cmi
FAILED: src/tea_json.cmj /Users/jackalcooper/elixir/missing_pieces/assets/node_modules/bucklescript-tea/lib/js/src/tea_json.js src/tea_json.cmi 
/usr/local/lib/node_modules/bs-platform/bin/bsc.exe -bs-package-name bucklescript-tea  -bs-package-output commonjs:lib/js/src -bs-assume-no-mli -bs-no-builtin-ppx-ml -bs-no-implicit-include  -I src  -nostdlib -I '/Users/jackalcooper/elixir/missing_pieces/assets/node_modules/bs-platform/lib/ocaml' -bs-cross-module-opt -no-alias-deps -color always -w -40+6+7+27+32..39+44+45 -o src/tea_json.mlast -c  src/tea_json.mlast 
File "/Users/jackalcooper/elixir/missing_pieces/assets/node_modules/bucklescript-tea/src/tea_json.ml", line 30, characters 16-26:
Error: Unbound value reify_type
Hint: Did you mean reifyType?
```

**Comment by jackalcooper** [comment]
Sent a pull request

**Comment by jackalcooper** [comment]
Now I got this error
```
FAILED: bs/main.cmj /Users/jackalcooper/elixir/missing_pieces/assets/lib/js/bs/main.js bs/main.cmi 
/Users/jackalcooper/elixir/missing_pieces/assets/node_modules/bs-platform/bin/bsc.exe -bs-package-name bucklescript_app  -bs-package-output commonjs:lib/js/bs -bs-assume-no-mli -bs-no-builtin-ppx-ml -bs-no-implicit-include -I /Users/jackalcooper/elixir/node_modules/bucklescript-tea/lib/ocaml -I bs  -nostdlib -I '/Users/jackalcooper/elixir/missing_pieces/assets/node_modules/bs-platform/lib/ocaml' -no-alias-deps -color always -w -40+6+7+27+32..39+44+45 -o bs/main.mlast -c  bs/main.mlast 
File "/Users/jackalcooper/elixir/missing_pieces/assets/bs/main.ml", line 1, characters 0-0:
Error: The files /Users/jackalcooper/elixir/node_modules/bucklescript-tea/lib/ocaml/tea_app.cmi
       and /Users/jackalcooper/elixir/missing_pieces/assets/node_modules/bs-platform/lib/ocaml/js.cmi
       make inconsistent assumptions over interface Js
```

**Comment by jackalcooper** [comment]
Fail to build even a counter example

**Comment by OvermindDL1** [comment]
Yeah I really really wish Bucklescript would quite breaking the API with simple naming changes (plus I like snake_case ^.^).  Thanks much!  Merged your PR.  :-)

**Comment by OvermindDL1** [comment]
Having to bump the minimum Bucklescript version as well, thus a new full version of this library too due to Bucklescript's change.

**Comment by OvermindDL1** [comment]
The JSON API changed more than just a name, but this is enough for it to work for now, I'll overhaul it later so it will be more future-proof with Bucklescripts upcoming changes too.  :-)

**Comment by OvermindDL1** [comment]
And published, closing issue.  Thanks much!!  :-D

**Comment by jackalcooper** [comment]
Yeah I know there is more under the water because I saw that issue you were talking about this. Probably we should set up a CI so we will know if a new Bucklescript release break things immediately.

**Comment by bobzhang** [comment]
sorry about the breakage, it would be nice that deprecated warnings are addressed properly

**Comment by OvermindDL1** [comment]
> sorry about the breakage, it would be nice that deprecated warnings are addressed properly

All good, it is mostly just semver.  :-)

With a backward incompatible API change the major version should be bumped, which is what most NPM versioning expects, if that were the case then a newer Bucklescript, say, 2.0.0 would not have even been recognized by mine by NPM.  :-)

As Teat is still < 1.0.0, it is similar but shifted right, so I bumped from 0.6.1 to 0.7.0 on the API incompatible change, and would bump to, say, 0.7.1 on a new feature added that was backwards compatible.  :-)
