### ISSUE TITLE
Uncaught TypeError: style.setProperty_ is not a function

### ISSUE THREAD

**Issue by neonsquare** [OvermindDL1/bucklescript-tea#15]
When I compile with BS 1.5.0 the following function breaks:

```javascript
function setStyleProperty(n, $staropt$star, key, value) {
  var priority = $staropt$star ? $staropt$star[0] : /* false */0;
  var style = n.style;
  var match = style.setProperty;
  if (match !== undefined) {
    return style.setProperty_(key, value, priority ? "important" : null);
  }
  else {
    return setStyle(n, key, value);
  }
}
```

In web_node.ml there is a type definition for 'style'

```ocaml
type style = <
   setProperty : Web_json.t Js.undefined [@bs.get]; (* TODO:  Revamp this and the next line... *)
   setProperty_ : string -> string Js.null -> string Js.null -> unit [@bs.meth];
   > Js.t
```

**Comment by bobzhang** [comment]
ah, it is probably because of a recent change of name mangling, we use `__` as overloading, the rational is single  underscore is used a lot in snake case  , so here you need `setProperty__` in the second

**Comment by OvermindDL1** [comment]
Hehe, Bucklescript broke the code.  ^.^

I see the PR to fix it in https://github.com/OvermindDL1/bucklescript-tea/pull/16/files and accepting it now.  Thanks @neonsquare!  :-)

I'll re-deploy to npm in a few minutes.  :-)
